#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo "Utilizare: $0 <fisier html>" 
	exit 1
fi

infile="$1"

if [ ! -f "$infile" ]; then
	echo "Eroare: fisierul '$infile' nu exista."
	exit 1
fi	


text=$(cat "$infile")

# folosesc array-ul ca si un stack
# stack[${#stack[*]}]="<body>" devine push
# unset stack[${#stack[@]}-1] devine pop
# echo "${#stack[@]}" -- inaltimea stivei

tabdepth=0

stack=( )

re='^<[[:space:]]*/[[:space:]]*([[:alnum:]_:-]+)'

last_end=0

after_label=1


put_content() {
	if [[ ${text:last_end:1} == $'\n' ]]; then
		((last_end++))
	fi	
	if [[ ${text:$((start-1)):1} == $'\n' ]]; then
		((start--))
	fi

	len=$(( start - last_end ))
	if [ "$len" -gt 0 ]; then
		section="${text:last_end:len}"
		if [[ $section == *[!$' \t\n\r']* ]]; then
			printf '%*s%s' "$((tabdepth*2))" "" "$section"
			after_label=0
		fi
	fi
}
#*[!$' \t\n\r']*
put_label(){
	if [ "$after_label" -eq 1 ]; then
		printf '%*s%s\n' "$(((tabdepth)*2))" "" "$label"
	else
		printf '\n%*s%s\n' "$(((tabdepth)*2))" "" "$label"
	fi
	after_label=1
}


while IFS=: read start label; do
	end=$(( start + ${#label} - 1))
	if [ "$label" == "<!doctype html>" ] || [ "$label" == "<!DOCTYPE html>" ]; then 
		printf '%s\n' "$label"	
		last_end=$((end+1))	
#	elif [ "$label" == "<html>" ] || [ "$label" == "</html>" ]; then
#		#len=$(( start - last_end ))
#		#printf '%*s%s' "$(((tabdepth)*2))" "" "${text:last_end:len}"
#		put_content
#		last_end=$((end+1))	
#		printf '%s\n' "$label"
#		after_label=1
	else
		if [[ $label =~ $re ]]; then
			#len=$(( start - last_end ))
			#printf '%*s%s' "$(((tabdepth)*2))" "" "${text:last_end:len}"
			put_content
			last_end=$((end+1))	
			
			stripped="${BASH_REMATCH[1]}"
			if [[ ${stack[-1]} != $stripped ]]; then
				echo "Eroare: eticheta ${stack[-1]} nu corespunde cu $stripped."
				exit 1	
			else
				((tabdepth--))	
				#printf '\n%*s%s' "$(((tabdepth-1)*2))" "" "$label"
				put_label
				unset stack[${#stack[@]}-1]
			fi
		elif [[ "$label" == '<!--'* ]]; then
			#len=$(( start - last_end ))
			#printf '%*s%s' "$(((tabdepth)*2))" "" "${text:last_end:len}"
			put_content
			last_end=$((end+1))	
			#printf '\n%*s%s\n' "$(((tabdepth)*2))" "" "$label"
			put_label
			
		else
			#len=$(( start - last_end ))
			#printf '%*s%s' "$(((tabdepth)*2))" "" "${text:last_end:len}"
			put_content
			last_end=$((end+1))	
			#printf '\n%*s%s\n' "$(((tabdepth)*2))" "" "$label"
			put_label
			label="${label:1}"
			label=$(echo $label | awk '{print $1}')	
			label=${label%>}
			case "$label" in 
				area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)
					;;
				*)
					stack[${#stack[*]}]="$label"
					((tabdepth++))
#					echo "Stiva: ${stack[@]}"
			esac
		fi
	fi
done < <(printf '%s' "$text" | grep -boE '<[^>]*>') 

if ((${#stack[@]})); then
	echo "Eroare: tag-uri neinchise: ${stack[*]}"
	exit 1
fi
