#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo "Utilizare: $0 <fisier html>" 
	exit 1
fi

infile="$1"

if [ ! -f "$infile" ]; then
	echo "Eroare: fisierul '$infile' nu exista."
	exit 1
fi	


text=$(cat "$infile")

# folosesc array-ul ca si un stack
# stack[${#stack[*]}]="<body>" devine push
# unset stack[${#stack[@]}-1] devine pop
# echo "${#stack[@]}" -- inaltimea stivei

tabdepth=0

stack=( )

re='^<[[:space:]]*/[[:space:]]*([[:alnum:]_:-]+)'

last_end=-1

while IFS=: read start label; do
	end=$(( start + ${#label} - 1))
	if [ "$label" == "<!doctype html>" ] || [ "$label" == "<!DOCTYPE html>" ]; then 
		printf '%s' "$label"	
		last_end=$((end+1))	
	elif [ "$label" == "<html>" ] || [ "$label" == "</html>" ]; then
		len=$(( start - last_end ))
		printf '%*s%s\n' "$(((tabdepth)*2))" "" "${text:last_end:len}"
		last_end=$((end+1))	
		printf '%s' "$label"	
	else
		if [[ $label =~ $re ]]; then
			len=$(( start - last_end ))
			printf '%*s%s\n' "$(((tabdepth)*2))" "" "${text:last_end:len}"
			last_end=$((end+1))	
			
			stripped="${BASH_REMATCH[1]}"
			if [[ ${stack[-1]} != $stripped ]]; then
				echo "Eroare: eticheta ${stack[-1]} nu corespunde cu $stripped."
				exit 1	
			else
				printf '%*s%s\n' "$(((tabdepth-1)*2))" "" "$label"
				unset stack[${#stack[@]}-1]
				((tabdepth--))	
			fi
		elif [[ "$label" == '<!--'* ]]; then
			len=$(( start - last_end ))
			printf '%*s%s\n' "$(((tabdepth)*2))" "" "${text:last_end:len}"
			last_end=$((end+1))	
			printf '%*s%s\n' "$(((tabdepth)*2))" "" "$label"
		else
			len=$(( start - last_end ))
			printf '%*s%s\n' "$(((tabdepth)*2))" "" "${text:last_end:len}"
			last_end=$((end+1))	
			printf '%*s%s\n' "$(((tabdepth)*2))" "" "$label"
			label="${label:1}"
			label=$(echo $label | awk '{print $1}')	
			label=${label%>}
			case "$label" in 
				area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)
					;;
				*)
					stack[${#stack[*]}]="$label"
					((tabdepth++))
#					echo "Stiva: ${stack[@]}"
			esac
		fi
	fi
done < <(printf '%s' "$text" | grep -boE '<[^>]*>') 

